version: '3.8'

services:
  backend:
    build: ./backend
    container_name: hotel_backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=localhost
      - DB_USER=escHotelT5
      - DB_PASSWORD=12345
      - DB_NAME=hotelbookingapp
    network_mode: "host"